environment:
  max_episode_steps: 1000
  name: HumanoidStable-v4
evaluation:
  eval_deterministic: true
  n_eval_episodes: 5
  record_videos: false
experiment:
  name: stand_still_training
  seed: 42
instructions:
  basic:
  - stand still
  - stop moving
motion_gpt:
  checkpoint_path: null
  config_path: null
training:
  checkpoint_freq: 5000
  eval_freq: 5000
  language_reward_weights:
  - 0.2
  n_parallel_envs: 2
  total_timesteps_per_instruction: 30000
